#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<EOSQL
CREATE ROLE ${OPENMETADATA_DB_USER} LOGIN PASSWORD '${OPENMETADATA_DB_PASSWORD}';
CREATE DATABASE ${OPENMETADATA_DB} OWNER ${OPENMETADATA_DB_USER};
CREATE ROLE ${TRINO_DB_USER} LOGIN PASSWORD '${TRINO_DB_PASSWORD}';
CREATE DATABASE ${FINANCIAL_DB} OWNER ${POSTGRES_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$FINANCIAL_DB" <<EOSQL
CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION ${POSTGRES_USER};
CREATE SCHEMA IF NOT EXISTS analytics AUTHORIZATION ${POSTGRES_USER};
GRANT CONNECT ON DATABASE ${FINANCIAL_DB} TO ${TRINO_DB_USER};
GRANT USAGE ON SCHEMA raw, analytics TO ${TRINO_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT SELECT ON TABLES TO ${TRINO_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT ON TABLES TO ${TRINO_DB_USER};
EOSQL
